version: '3'

services:
  app:
    image: python:3.9
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "pip3 install -r requirements.txt && uvicorn main:app --reload --host=0.0.0.0"
    container_name: app
    ports:
      - 8000:8000